CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    birth_date DATE,
    gender VARCHAR(10),
    nickname VARCHAR(50),
    login_provider VARCHAR(30),
    provider_id VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_login_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS content_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    summary VARCHAR(300),
    body TEXT NOT NULL,
    source_url VARCHAR(300),
    author VARCHAR(60) NOT NULL,
    category VARCHAR(30) NOT NULL,
    approval_status VARCHAR(20) NOT NULL,
    approval_comment VARCHAR(500),
    approved_by VARCHAR(100),
    approved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    author VARCHAR(60) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS community_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    body TEXT NOT NULL,
    author VARCHAR(60) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS code_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description TEXT,
    language VARCHAR(40) NOT NULL,
    source_code TEXT NOT NULL,
    author_email VARCHAR(100) NOT NULL,
    purpose VARCHAR(120),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS code_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    reviewer_email VARCHAR(100) NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS code_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    user_email VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_submission_user UNIQUE (submission_id, user_email)
);

CREATE INDEX IF NOT EXISTS idx_community_comments_post_id ON community_comments (post_id);
CREATE INDEX IF NOT EXISTS idx_code_reviews_submission_id ON code_reviews (submission_id);
CREATE INDEX IF NOT EXISTS idx_code_likes_submission_id ON code_likes (submission_id);
