FROM openjdk:17-jdk-slim
WORKDIR /app
COPY /home/runner/work/everybodycodeacademy/everybodycodeacademy/everybodycodeacademy/build/libs/everycodeacademy-0.0.1-SNAPSHOT.jar /app/
CMD ["java", "-jar", "everycodeacademy-0.0.1-SNAPSHOT.jar"]
