name: Docker Image CICD
on:
  workflow_dispatch:
      
permissions:
  contents: read
  
jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
          run:
            working-directory: ./everycodeacademy

      steps:
        - uses: actions/checkout@v3.6.0
        - name: Set up JDK 17
          uses: actions/setup-java@v3.13.0
          with:
            java-version: '17'
            distribution: 'corretto'
  
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2.9.0

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
          
        - name: Build with Gradle
          run: ./gradlew clean build -x test
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: checkfiles
          run: ls -l

        - name: change dir
          run: |
            pwd
            ls -l
            
        - name: checkfiles
          run: ls -l

        - name: Cache PhysicalTheraphy build directory
          uses: actions/cache@v3
          with:
            path: ./
            key: ${{ runner.os }}-physicaltheraphy-build-cache-${{ steps.short-sha.outputs.sha }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: "{{defaultContext}}:${{ secrets.DOCKER_REPO }}"
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO }}
