name: Docker Image CICD
on:
  workflow_dispatch:
  
jobs:
  test:
      runs-on: ubuntu-latest
      env: 
         working-directory: ./everycodeacademy

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'
          
        - name: Build with Gradle
          working-directory: ${{ env.working-directory }}
          run: |
            ./gradlew clean build -x test
            pwd
            ls
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Docker build & push
          working-directory: ${{ env.working-directory }}
          run: |
           pwd
           ls -l
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}} .
           docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}}
