name: Docker Image CICD
on:
  push:
    branches: everycodeacademy
  pull_request:
    branches: 
      - main
      - everycodeacademy_cicd
env:
  # docker hub의 organization 이름
  REGISTRY: "xenex90"
  # build and push 할 docker image 이름
  IMAGE_NAME: "everycodeacademy"
  # build and push 할 docker image의 tag
  TAG: "latest"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle build
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v3
      - name: Build the Docker image  
        run: docker build --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Push the Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
