name: Docker Image CICD
on:
  workflow_dispatch:
      
permissions:
  contents: read
  
jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
          run:
            working-directory: ./everycodeacademy

      steps:
        - uses: actions/checkout@v3.6.0
        - name: Set up JDK 17
          uses: actions/setup-java@v3.13.0
          with:
            java-version: '17'
            distribution: 'corretto'
  
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2.9.0

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
          
        - name: Build with Gradle
          run: ./gradlew --build-cache -x test
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: change dir
          run: |
            pwd
            ls -l
            
        - name: checkfiles
          run: ls -l

        - name: Docker build & push
          run: |
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}} .
           docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}}
