name: Docker Image CICD
on:
  workflow_dispatch:
  
jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'corretto'
          
        - name: Build with Gradle
          working-directory: /home/runner/work/everybodycodeacademy/everybodycodeacademy
          run: | 
            pwd
            ls -l
            ./gradlew --build-cache -x test
            pwd
            ls
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: change dir
          run: |
            pwd
            ls -l
            
        - name: checkfiles
          run: ls

        - name: Docker build & push
          working-directory: /home/runner/work/everybodycodeacademy/everybodycodeacademy
          run: |
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}} .
           docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPO}}
