name: Docker Image CICD
on:
  push:
    branches: 
    - everycodeacademy
  pull_request:
    branches: 
    - main
    - everycodeacademy_cicd
      
permissions:
  contents: read
  
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3.6.0
        - name: Set up JDK 17
          uses: actions/setup-java@v3.13.0
          with:
            java-version: '17'
            distribution: 'corretto'
  
       
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2.9.0
          
        - name: Build with Gradle
          run: ./gradlew clean build -x test
  
        #- name: Login to DockerHub
        - name: Build and Push to DockerHub
          uses: MaximilianoBz/dockerhub-buildpush@v1.1
          with:
            # Docker Registry Url, eg: docker.io
            registry_url: docker.io
            # Docker Image Repository Name, eg: username/demo-app
            repository_name: ${{ secrets.DOCKER_REPO }}
            # Docker Login UserName, from: https://hub.docker.com/
            user_name: ${{ secrets.DOCKERHUB_USERNAME }}
            # Docker Login Access Token, from: https://hub.docker.com/
            password: ${{ secrets. DOCKERHUB_PASSWORD }}
            # Image Build Version
            image_version: latest

